version: '3.8'

services:
  txTracker:
    image: node:18-alpine
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../:/app
    networks:
      - host

networks:
  host:
    name: host
    external: true